services:
  groupmemail:
    build: .
    environment:
      SCHEME: http
      SECRET_KEY: (set in compose.override.yaml)
      SERVER_NAME: localhost:8080
    image: ghcr.io/williamjacksn/groupmemail
    init: true
    ports:
      - 8080:8080

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/groupmemail
    init: true
    volumes:
      - ./:/home/python/groupmemail
    working_dir: /home/python/groupmemail
