services:
  groupmemail:
    build: .
    environment:
      GROUPME_CLIENT_ID: (set in compose.override.yaml)
      MAILGUN_API_KEY: (set in compose.override.yaml)
      MAILGUN_DOMAIN: (set in compose.override.yaml)
      SCHEME: http
      SECRET_KEY: (set in compose.override.yaml)
      SERVER_NAME: localhost:8080
      STRIPE_PUBLISHABLE_KEY: (set in compose.override.yaml)
      STRIPE_SECRET_KEY: (set in compose.override.yaml)
      STRIPE_SKU: (set in compose.override.yaml)
      STRIPE_WEBHOOK_SECRET: (set in compose.override.yaml)
    image: ghcr.io/williamjacksn/groupmemail
    init: true
    ports:
      - 8080:8080

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresl/data/11
    image: postgres:11.11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/groupmemail
    init: true
    volumes:
      - ./:/home/python/groupmemail
    working_dir: /home/python/groupmemail

volumes:
  postgres-data:
