version: '3.8'

services:
  groupmemail:
    build: .
    environment:
      ADMIN_EMAIL: (set in docker-compose.override.yaml)
      DSN: postgres://postgres:postgres@postgres/postgres
      EMAIL_SENDER: (set in docker-compose.override.yaml)
      GROUPME_CLIENT_ID: (set in docker-compose.override.yaml)
      MAILGUN_API_KEY: (set in docker-compose.override.yaml)
      MAILGUN_DOMAIN: (set in docker-compose.override.yaml)
      SCHEME: http
      SECRET_KEY: (set in docker-compose.override.yaml)
      SERVER_NAME: localhost:8080
      STRIPE_PUBLISHABLE_KEY: (set in docker-compose.override.yaml)
      STRIPE_SECRET_KEY: (set in docker-compose.override.yaml)
      STRIPE_SKU: (set in docker-compose.override.yaml)
      STRIPE_WEBHOOK_SECRET: (set in docker-compose.override.yaml)
    image: ghcr.io/williamjacksn/groupmemail
    init: true
    ports:
      - 8080:8080

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresl/data/11
    image: postgres:11.11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
